---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-domain-events-preprod-admin
  namespace: hmpps-domain-events-preprod
subjects:
  - kind: Group
    name: "github:dps-shared"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:dps-core"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dps-ingress-manager
  namespace: hmpps-domain-events-preprod
subjects:
  - kind: ServiceAccount
    name: dps-ingress-manager
    namespace: dps-management-preprod
roleRef:
  kind: ClusterRole
  name: dps-ingress-manager
  apiGroup: rbac.authorization.k8s.io
