apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: pathfinder-dev

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: pathfinder-dev
subjects:
- kind: ServiceAccount
  name: circleci
  namespace: pathfinder-dev
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
