kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oasys-keycloak-prod-admin
  namespace: oasys-keycloak-prod
subjects:
  - kind: Group
    name: "github:sentencing-and-oasys-development-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: oasys-keycloak-prod
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: oasys-keycloak-prod
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: oasys-keycloak-prod
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: oasys-keycloak-prod
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oasys-keycloak-prod-circleci
  namespace: oasys-keycloak-prod
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: oasys-keycloak-prod
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
