apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: hmpps-ppm-api-dev.prison.service.justice.gov.uk
  namespace: hmpps-pin-phone-monitor-dev
spec:
  secretName: hmpps-pin-phone-monitor-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - pin-phone-monitor-api-dev.prison.service.justice.gov.uk
