apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: laa-court-data-adaptor
  namespace: laa-court-data-adaptor-test
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: laa-court-data-adaptor
  namespaceSelector:
    matchNames:
      - laa-court-data-adaptor-test
  endpoints:
    - port: http
      interval: 15s
