kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: check-my-diary-dev-admin
  namespace: check-my-diary-dev
subjects:
  - kind: Group
    name: "github:check-my-diary"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
