---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus
  namespace: hmpps-ems-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: gp2-expand