apiVersion: v1
kind: ServiceAccount
metadata:
  name: "circleci-formbuilder-saas-test"
  namespace: "formbuilder-saas-test"

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "circleci-formbuilder-saas-test"
  namespace: "formbuilder-saas-test"
rules:
  - apiGroups:
      - ""
    resources:
      - "pods/portforward"
      - "deployment"
      - "secrets"
      - "services"
      - "pods"
      - "configmaps"
    verbs:
      - "patch"
      - "get"
      - "create"
      - "delete"
      - "list"
      - "watch"
  - apiGroups:
      - "extensions"
      - "apps"
      - "networking.k8s.io"
      - "monitoring.coreos.com"
    resources:
      - "deployments"
      - "ingresses"
      - "networkpolicies"
      - "servicemonitors"
    verbs:
      - "get"
      - "update"
      - "delete"
      - "create"
      - "patch"
      - "list"
      - "watch"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "circleci-formbuilder-saas-test"
  namespace: "formbuilder-saas-test"
subjects:
- kind: ServiceAccount
  name: "circleci-formbuilder-saas-test"
  namespace: "formbuilder-saas-test"
roleRef:
  kind: Role
  name: "circleci-formbuilder-saas-test"
  apiGroup: rbac.authorization.k8s.io
