apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: check-financial-eligibility-production

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: check-financial-eligibility-production
rules:
  - apiGroups:
      - ""
    resources:
      - "pods/portforward"
      - "deployment"
      - "secrets"
      - "services"
      - "pods"
    verbs:
      - "patch"
      - "get"
      - "create"
      - "update"
      - "delete"
      - "list"
  - apiGroups:
      - "extensions"
      - "apps"
      - "networking.k8s.io"
      - "batch"
    resources:
      - "deployments"
      - "ingresses"
      - "statefulsets"
      - "replicasets"
    verbs:
      - "get"
      - "update"
      - "delete"
      - "create"
      - "patch"
      - "list"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: check-financial-eligibility-production
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: check-financial-eligibility-production
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io
