apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: book-a-prison-visit-development

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: book-a-prison-visit-development
subjects:
- kind: ServiceAccount
  name: circleci
  namespace: book-a-prison-visit-development
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
