kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: delius-updates-prod-admin
  namespace: delius-updates-prod
subjects:
  - kind: Group
    name: "github:manage-a-sentence"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: delius-updates-prod
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: delius-updates-prod-circleci
  namespace: delius-updates-prod
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: delius-updates-prod
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
