apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: delius-updates.service.justice.gov.uk
  namespace: delius-updates-prod
spec:
  secretName: delius-updates-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - delius-updates.service.justice.gov.uk
