---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: probation-case-sampler-dev-admin
  namespace: probation-case-sampler-dev
subjects:
  - kind: Group
    name: "github:dps-shared"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dps-ingress-manager
  namespace: probation-case-sampler-dev
subjects:
  - kind: ServiceAccount
    name: dps-ingress-manager
    namespace: dps-management-dev
roleRef:
  kind: ClusterRole
  name: dps-ingress-manager
  apiGroup: rbac.authorization.k8s.io
