apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: manage-key-workers-prod

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: manage-key-workers-prod
subjects:
- kind: ServiceAccount
  name: circleci
  namespace: manage-key-workers-prod
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
