---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: audit-api-preprod.hmpps.service.justice.gov.uk
  namespace: hmpps-audit-preprod
spec:
  secretName: audit-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - audit-api-preprod.hmpps.service.justice.gov.uk
