---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus
  namespace: hmpps-ems-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 75Gi
  storageClassName: gp2-expand