kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: court-probation-prod-admin
  namespace: court-probation-prod
subjects:
  - kind: Group
    name: "github:ndelius"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
