kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: interventions-catalogue-ui-dev-admin
  namespace: interventions-catalogue-ui-dev
subjects:
  - kind: Group
    name: "github:interventions-catalogue"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
