apiVersion: v1
kind: Namespace
metadata:
  name: c100-application-metabase
  labels:
    cloud-platform.justice.gov.uk/is-production: "true"
    cloud-platform.justice.gov.uk/environment-name: "production"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HQ"
    cloud-platform.justice.gov.uk/application: "Apply to court about child arrangements - Metabase"
    cloud-platform.justice.gov.uk/owner: "UCPD Cross Justice Delivery: crossjusticedelivery@digital.justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/c100-application"
    cloud-platform.justice.gov.uk/slack-channel: "cross_justice_team"
    cloud-platform.justice.gov.uk/team-name: "family-justice"
