---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dps-management-prod-admin
  namespace: dps-management-prod
subjects:
  - kind: Group
    name: "github:dps-shared"
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "github:dps-tech"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
