---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: dps-rds-monitoring
    prometheus: cloud-platform
  name: dps-rds-monitoring-rules
  namespace: dps-management-prod
spec:
  groups:
  - name: DPS-RDS
    rules:
    - alert: rds-free-storage-keyworker-api-prod
      annotations:
        message: RDS instance running low on storage - keyworker-api-prod
      expr: |-
        aws_rds_free_storage_space_average{dbinstance_identifier="cloud-platform-fa888e83362e61b1"} offset 10m < 2e+09
      for: 5m
      labels:
        severity: digital-prison-service
    - alert: rds-cpu-utilization-keyworker-api-prod
      annotations:
        message: RDS CPU utilization is high - keyworker-api-prod
      expr: |-
        aws_rds_cpuutilization_average{dbinstance_identifier="cloud-platform-fa888e83362e61b1"} > 90
      for: 5m
      labels:
        severity: digital-prison-service

    - alert: rds-free-storage-licences-prod
      annotations:
        message: RDS instance running low on storage - licences-prod
      expr: |-
        aws_rds_free_storage_space_average{dbinstance_identifier="cloud-platform-a450784ed2b32c2e"} offset 10m < 2e+09
      for: 5m
      labels:
        severity: digital-prison-service
    - alert: rds-cpu-utilization-licences-prod
      annotations:
        message: RDS CPU utilization is high - licences-prod
      expr: |-
        aws_rds_cpuutilization_average{dbinstance_identifier="cloud-platform-a450784ed2b32c2e"} > 90
      for: 5m
      labels:
        severity: digital-prison-service

    - alert: rds-free-storage-manage-soc-cases-prod
      annotations:
        message: RDS instance running low on storage - manage-soc-cases-prod
      expr: |-
        aws_rds_free_storage_space_average{dbinstance_identifier="cloud-platform-929fc5abb8e62ee3"} offset 10m < 2e+09
      for: 5m
      labels:
        severity: digital-prison-service
    - alert: rds-cpu-utilization-manage-soc-cases-prod
      annotations:
        message: RDS CPU utilization is high - manage-soc-cases-prod
      expr: |-
        aws_rds_cpuutilization_average{dbinstance_identifier="cloud-platform-929fc5abb8e62ee3"} > 90
      for: 5m
      labels:
        severity: digital-prison-service

    - alert: rds-free-storage-offender-case-notes-prod
      annotations:
        message: RDS instance running low on storage - offender-case-notes-prod
      expr: |-
        aws_rds_free_storage_space_average{dbinstance_identifier="cloud-platform-b6244d8c893e1d12"} offset 10m < 2e+09
      for: 5m
      labels:
        severity: digital-prison-service
    - alert: rds-cpu-utilization-offender-case-notes-prod
      annotations:
        message: RDS CPU utilization is high - offender-case-notes-prod
      expr: |-
        aws_rds_cpuutilization_average{dbinstance_identifier="cloud-platform-b6244d8c893e1d12"} > 90
      for: 5m
      labels:
        severity: digital-prison-service

    - alert: rds-free-storage-offender-categorisation-prod
      annotations:
        message: RDS instance running low on storage - offender-categorisation-prod
      expr: |-
        aws_rds_free_storage_space_average{dbinstance_identifier="cloud-platform-7da276da34a30306"} offset 10m < 2e+09
      for: 5m
      labels:
        severity: digital-prison-service
    - alert: rds-cpu-utilization-offender-categorisation-prod
      annotations:
        message: RDS CPU utilization is high - offender-categorisation-prod
      expr: |-
        aws_rds_cpuutilization_average{dbinstance_identifier="cloud-platform-7da276da34a30306"} > 90
      for: 5m
      labels:
        severity: digital-prison-service

    - alert: rds-free-storage-offender-events-prod
      annotations:
        message: RDS instance running low on storage - offender-events-prod
      expr: |-
        aws_rds_free_storage_space_average{dbinstance_identifier="cloud-platform-f571ef4833323931"} offset 10m < 2e+09
      for: 5m
      labels:
        severity: digital-prison-service
    - alert: rds-cpu-utilization-offender-events-prod
      annotations:
        message: RDS CPU utilization is high - offender-events-prod
      expr: |-
        aws_rds_cpuutilization_average{dbinstance_identifier="cloud-platform-f571ef4833323931"} > 90
      for: 5m
      labels:
        severity: digital-prison-service

    - alert: rds-free-storage-pathfinder-prod
      annotations:
        message: RDS instance running low on storage - pathfinder-prod
      expr: |-
        aws_rds_free_storage_space_average{dbinstance_identifier="cloud-platform-5dbdcc77ff9d954a"} offset 10m < 2e+09
      for: 5m
      labels:
        severity: digital-prison-service
    - alert: rds-cpu-utilization-pathfinder-prod
      annotations:
        message: RDS CPU utilization is high - pathfinder-prod
      expr: |-
        aws_rds_cpuutilization_average{dbinstance_identifier="cloud-platform-5dbdcc77ff9d954a"} > 90
      for: 5m
      labels:
        severity: digital-prison-service

    - alert: rds-free-storage-prison-data-compliance-prod
      annotations:
        message: RDS instance running low on storage - prison-data-compliance-prod
      expr: |-
        aws_rds_free_storage_space_average{dbinstance_identifier="cloud-platform-06589e91e5b00501"} offset 10m < 2e+09
      for: 5m
      labels:
        severity: digital-prison-service
    - alert: rds-cpu-utilization-prison-data-compliance-prod
      annotations:
        message: RDS CPU utilization is high - prison-data-compliance-prod
      expr: |-
        aws_rds_cpuutilization_average{dbinstance_identifier="cloud-platform-06589e91e5b00501"} > 90
      for: 5m
      labels:
        severity: digital-prison-service

    - alert: rds-free-storage-prison-estate-prod
      annotations:
        message: RDS instance running low on storage - prison-estate-prod
      expr: |-
        aws_rds_free_storage_space_average{dbinstance_identifier="cloud-platform-3da292d237ae6585"} offset 10m < 2e+09
      for: 5m
      labels:
        severity: digital-prison-service
    - alert: rds-cpu-utilization-prison-estate-prod
      annotations:
        message: RDS CPU utilization is high - prison-estate-prod
      expr: |-
        aws_rds_cpuutilization_average{dbinstance_identifier="cloud-platform-3da292d237ae6585"} > 90
      for: 5m
      labels:
        severity: digital-prison-service

    - alert: rds-free-storage-prison-to-nhs-update-prod
      annotations:
        message: RDS instance running low on storage - prison-to-nhs-update-prod
      expr: |-
        aws_rds_free_storage_space_average{dbinstance_identifier="cloud-platform-b3b53f95ba1f6870"} offset 10m < 2e+09
      for: 5m
      labels:
        severity: digital-prison-service
    - alert: rds-cpu-utilization-prison-to-nhs-update-prod
      annotations:
        message: RDS CPU utilization is high - prison-to-nhs-update-prod
      expr: |-
        aws_rds_cpuutilization_average{dbinstance_identifier="cloud-platform-b3b53f95ba1f6870"} > 90
      for: 5m
      labels:
        severity: digital-prison-service

    - alert: rds-free-storage-use-of-force-prod
      annotations:
        message: RDS instance running low on storage - use-of-force-prod
      expr: |-
        aws_rds_free_storage_space_average{dbinstance_identifier="cloud-platform-1fb65a0439ba05e6"} offset 10m < 2e+09
      for: 5m
      labels:
        severity: digital-prison-service
    - alert: rds-cpu-utilization-use-of-force-prod
      annotations:
        message: RDS CPU utilization is high - use-of-force-prod
      expr: |-
        aws_rds_cpuutilization_average{dbinstance_identifier="cloud-platform-1fb65a0439ba05e6"} > 90
      for: 5m
      labels:
        severity: digital-prison-service

    - alert: rds-free-storage-whereabouts-api-prod
      annotations:
        message: RDS instance running low on storage - whereabouts-api-prod
      expr: |-
        aws_rds_free_storage_space_average{dbinstance_identifier="cloud-platform-67257a8b15c64e7f"} offset 10m < 2e+09
      for: 5m
      labels:
        severity: digital-prison-service
    - alert: rds-cpu-utilization-whereabouts-api-prod
      annotations:
        message: RDS CPU utilization is high - whereabouts-api-prod
      expr: |-
        aws_rds_cpuutilization_average{dbinstance_identifier="cloud-platform-67257a8b15c64e7f"} > 90
      for: 5m
      labels:
        severity: digital-prison-service