apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prison-to-probation-update
  namespace: prison-to-probation-update-prod
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prison-to-probation-update
  namespaceSelector:
    matchNames:
      - prison-to-probation-update-prod
  endpoints:
    - port: http
      path: /prometheus
      interval: 15s
