apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: dev.delius-updates.service.justice.gov.uk
  namespace: delius-updates-dev
spec:
  secretName: delius-updates-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - dev.delius-updates.service.justice.gov.uk
