apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: c100-application-staging
spec:
  limits:
  - default:
      cpu: 250m
      memory: 500Mi
    defaultRequest:
      cpu: 10m
      memory: 100Mi
    type: Container
