kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: proffeapp-dev-admin
  namespace: proffeapp-dev
subjects:
  - kind: Group
    name: "github:hmpps-dev-test"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
