apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: contact-moj-service
spec:
  selector:
    matchLabels:
      app: contact-moj-service
  endpoints:
  - port: http
    interval: 15s