apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: offender-categorisation-dev
spec:
  limits:
  - default:
      cpu: 2000m
      memory: 1024Mi
    defaultRequest:
      cpu: 10m
      memory: 512Mi
    type: Container
