apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: sentence-planning-development
spec:
  limits:
  - default:
      cpu: 2000m
      memory: 1500Mi
    defaultRequest:
      cpu: 10m
      memory: 100Mi
    type: Container
